baseURL = "https://solangii.github.io/"
title = "Solang Kim"
author = "Solang Kim"
description = "Solang Kim's blog"

copyright = "Copyright © 2022, Solang Kim; all rights reserved."

languageCode = "ko-kr"
DefaultContentLanguage = "ko-kr"

enableRobotsTXT = true
enableEmoji = true

paginate = 5

enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]
summaryLength = 20


[params]
  email = 'solangii@unist.ac.kr'
  github = 'solangii'
  instagram = 's_rang__'
  logo = "logo.png"

  math = true
  mathjax = true
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" 
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" 


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]

